
name: compiling kernel

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

env:
  KERNEL_SOURCE: https://github.com/darkhz/revvz_sakura.git
  BRANCH: beta-4.9-Q
  DEFCONFIG: sakura_defconfig
  TZ: Asia/Kolkata
  MIR: bit
  TOOLCHAIN: https://github.com/mscalindt/aarch64-linux-android-4.9.git
  ARCH: arm64
  SUBARCH: arm64
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison ccache
       - name: Cloning repo
         run: |
            git clone --recurse-submodules $KERNEL_SOURCE --depth=1 --branch=$BRANCH work
       - name: Compiling Kernel
         run: |
            cd work
            git clone $TOOLCHAIN --depth=1
            CROSS_COMPILE+="aarch64-linux-android-4.9/bin/aarch64-linux-android-"
            export CROSS_COMPILE
            export ARCH=$ARCH && export SUBARCH=$SUBARCH
            make clean
            make O=/home/runner/work/kernel-automation/kernel-automation/work $DEFCONFIG
            make O=/home/runner/work/kernel-automation/kernel-automation/work -j8 --all
       - name: Uploading process
         run: |
            cd work/arch/arm64/boot
            curl -sL https://git.io/file-transfer | sh
            ./transfer $MIR Image.gz-dtb
